import java.awt.Graphics;

import java.applet.Applet;
public class ch extends javax.swing.JFrame {

    /**
     * Creates new form ch
     */
    public int a;
    public ch() {

    
        initComponents();
        choice1.addItem("rectangle");

         choice1.addItem("circle");

        choice1.addItem("triangle");

        choice1.addItem("square");
    }
public void paint(Graphics g){

           

         //System.out.println(a);

       

            if ( a==0 )

            {

              g.drawRect(120,80,40,70);  

            }

            else if ( a==1 )

            {

            g.drawOval(40,200,30,30);    

            }

            else if ( a==2 )

            {

                g.drawLine(180,150,180,370);

                g.drawLine(180,150,440,370);

                g.drawLine(180,370,440,370);

            }

            else if ( a==3 )

            {

                g.drawRect(100,200,50,50);

            }

 

 

     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        choice1 = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {                                         
               // TODO add your handling code here:
               a =choice1.getSelectedIndex();

       // System.out.println(a);

       /*if (evt.getSource() == choice1 )

            a = 1;*/

        repaint ();
    }             