 private void textField1MouseClicked(java.awt.event.MouseEvent evt) {                                        
      
        

    System.out.println("Mouse clicked.");


    }                                       

    private void textField1MouseEntered(java.awt.event.MouseEvent evt) {                                        
         System.out.println("Mouse entered.");
    }                                       

    private void textField1MousePressed(java.awt.event.MouseEvent evt) {                                        
      System.out.println("Mouse press.");
    }                                       

    private void textField1MouseReleased(java.awt.event.MouseEvent evt) {                                         
         System.out.println("Mouse released.");
    }                                        

    private void textField1MouseExited(java.awt.event.MouseEvent evt) {                                       
        System.out.println("Mouse exited.");
    }                                      
